apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    volume: app-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "root/data/app-data"
