kind: Pod
apiVersion: v1
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx:1.14.0
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: app-data
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: app-data-claim
